version: '3'

networks:
  socialdevelop-server-network:
    external: true

services:
  socialdevelop-server:
    container_name: socialdevelop-server
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html/
    networks:
      - socialdevelop-server-network
